# Inventory
[servers]
worker-node-1 ansible_host=<ip_address> ansible_user=ubuntu
worker-node-2 ansible_host=<ip_address> ansible_user=ubuntu

[all:vars]
ansible_ssh_private_key_file=/home/ubuntu/ansible_master_key
ansible_python_interpreter=/usr/bin/python3   # view by `which python` command
ansible_host_key_checking=false


# Commands
ansible -i <inv_file> servers -m ping
ansible -i <inv_file> servers -a "uptime"
ansible -i <inv_file> servers -a "sudo apt-get update"

# Setup NginX
---
- name: Setup Nginx
  become: yes
  hosts: servers

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: Copy custom HTML File
      copy:
        src: index.html
        dest: /var/www/html
    - name: Restart Nginx
      service:
        name: nginx
        state: reloaded
    - name: Enable Nginx
      systemd_service:
        name: nginx
        state: started
        enabled: yes



############ Roles ###############
ansible-galaxy init roles/docker

# tasks:
- name: Update apt cache
  apt:
    update_cache: yes
    
- name: Install Docker.io
  apt: 
    name: docker.io
    state: latest
    
- name: Add users to Docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"

# Handler
- name: Restart Docker
  service: 
    name: docker
    state: restarted
  become: yes

- name: Register Docker Version
  command: docker --version
  register: docker_version
    
- name: Show Docker Version
  debug:
    msg: "{{ docker_version }}"

- name: Show Running Containers
  command: docker ps

# Create Playbook
---
- name: Install Docker
  hosts: servers
  become: yes
  roles:
    - docker


# Push
ansible-galaxy import dakshsawhneyy dummy-ansible-role --token <token>
